### ISSUE TITLE
Enhancement: PodDecorations should show in Pod OwnerReferences

### ISSUE THREAD

**Issue by zoumo** [KusionStack/kuperator#259]
### What would you like to be added?

add PodDecoration in pod ownerReferences

### Why is this needed?

rollout need to identify effective PodDecorations for the pods. The best practice is to include PodDecorations in the ownerReferences of the pod.

**Comment by ColdsteelRail** [comment]
fixed in https://github.com/KusionStack/kuperator/pull/264
